apiVersion: v1                       # 使用 Kubernetes core API 的 v1 版本（PVC 屬於 core/v1）
kind: PersistentVolumeClaim          # 資源種類：PersistentVolumeClaim（向叢集「申請」一塊持久化儲存）

metadata:                            # 物件的基本資訊
  name: {學號}-pvc                   # PVC 名稱（Pod 之後會透過這個名稱掛載 storage）
  namespace: lab3                    # PVC 所在的 namespace（只有同 namespace 的 Pod 可以直接使用）

spec:                                # PVC 的規格設定
  accessModes:                       # 存取模式（定義這個 volume 可以怎麼被掛載）
    - ReadWriteOnce                  # RWO：一次只能被「一個 Node」掛載，但可以被該 Node 上多個 Pod 使用

  storageClassName: local-path       # 指定使用的 StorageClass（這裡用 local-path provisioner 自動建立 PV）

  resources:                         # PVC 申請的資源需求
    requests:                        # request 表示「至少需要多少空間」
      storage: 200Mi                 # 申請 200MiB 的儲存空間（K8s 會找或建立一個符合的 PersistentVolume）

