apiVersion: v1
kind: Service
metadata:
  name: lab3-svc
  namespace: lab3
spec:
  type: NodePort
  selector:
    app: lab3-pod
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30083

