apiVersion: apps/v1                 # 使用 apps/v1 API（Deployment 屬於 apps 群組）
kind: Deployment                    # 資源種類：Deployment（用來管理 ReplicaSet 與滾動更新）
metadata:                           # 基本資訊
  name: lab1-{學號}-deploy          # Deployment 名稱（cluster 內唯一）
spec:                               # Deployment 的規格設定
  replicas: 3                       # 希望維持 3 個 Pod（期望狀態）
  strategy:                         # 更新策略設定
    type: RollingUpdate             # 採用滾動更新（不中斷服務）
    rollingUpdate:                  # 滾動更新的具體設定
      maxSurge: 1                   # 更新時最多可以「多出」1 個 Pod（暫時 4 個）
      maxUnavailable: 1             # 更新時最多允許 1 個 Pod 不可用
  selector:                         # 用來選擇屬於這個 Deployment 的 Pod
    matchLabels:                    # 條件：標籤必須符合
      app: lab1-deploy-pod          # 只管理 label 為 app=lab1-deploy-pod 的 Pod
  template:                         # Pod 範本（Deployment 會用這個建立新的 ReplicaSet）
    metadata:
      labels:
        app: lab1-deploy-pod        # 必須與 selector.matchLabels 一致
        version: v1                 # 自訂版本標籤（可用於版本區分、分流觀察）
    spec:
      containers:
      - name: lab1-deploy-pod       # 容器名稱（Pod 內識別用）
        image: {docker_repo}:lab1   # 使用的 Docker Image（來自 docker hub repository）
        ports:
        - containerPort: 80         # 容器內監聽的 port（提供 HTTP 服務）
        env:
        - name: POD_NAME
          valueFrom: { fieldRef: { fieldPath: metadata.name } }
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        - name: POD_NAMESPACE
          valueFrom: { fieldRef: { fieldPath: metadata.namespace } }
        - name: NODE_NAME
          valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
        - name: NODE_IP
          valueFrom: { fieldRef: { fieldPath: status.hostIP } }
        - name: APP_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['version']

